// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// viewModeler is an autogenerated mock type for the viewModeler type
type viewModeler struct {
	mock.Mock
}

// ViewData provides a mock function with given fields:
func (_m *viewModeler) ViewData() map[string]interface{} {
	ret := _m.Called()

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

type mockConstructorTestingTnewViewModeler interface {
	mock.TestingT
	Cleanup(func())
}

// newViewModeler creates a new instance of viewModeler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newViewModeler(t mockConstructorTestingTnewViewModeler) *viewModeler {
	mock := &viewModeler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
