policies:
  - type: commit
    spec:
      header:
        length: 89
        case: lower
        invalidLastCharacters: .
      spellcheck:
        locale: US
      conventional:
        types:
          - "ci"
          - "docs"
          - "refactor"
          - "perf"
          - "feat"
          - "fix"
          - "chore"
          - "test"
        descriptionLength: 72