policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: true
      spellcheck:
        locale: US
      conventional:
        types:
          - "type"
        scopes:
          - "scope"
        descriptionLength: 72