// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// SendConfirmMail provides a mock function with given fields: email, code, language
func (_m *Mailer) SendConfirmMail(email string, code string, language string) error {
	ret := _m.Called(email, code, language)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(email, code, language)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendPasswordRecoverMail provides a mock function with given fields: email, code, language
func (_m *Mailer) SendPasswordRecoverMail(email string, code string, language string) error {
	ret := _m.Called(email, code, language)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(email, code, language)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMailer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMailer creates a new instance of Mailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMailer(t mockConstructorTestingTNewMailer) *Mailer {
	mock := &Mailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
